version: "3"
services:
  springboot-app:
    image: springboot-app
    restart: always
    build: .
    ports:
      - 9090:8082
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: miola
      MYSQL_ROOT_PASSWORD: root
  react-app:
    image: react-app
    build:
      context: ./src/main/webapp/reactjs
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: npm start
